apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-docker-env-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: localhost:5000/express-docker-env:latest
          imagePullPolicy: IfNotPresent
          name: api
          ports:
            - containerPort: 3000
          env:
            - name: MY_AWESOME_VARIABLE
              valueFrom:
                secretKeyRef:
                  name: my-awesome-secret
                  key: awesomeEnvironmentVariable
---
apiVersion: v1
kind: Service
metadata:
  name: express-docker-env-service
  labels:
    app: api
spec:
  type: 'LoadBalancer'
  ports:
    - protocol: TCP
      name: 'http'
      port: 3000
      targetPort: 3000
  selector:
    app: api
